_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 3
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.3
            "5": 0.19.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
activation:
    value: Tanh
batch_size:
    value: 64
epochs:
    value: 10
hidden_units:
    value: 512
learning_rate:
    value: 0.0001
optimizer:
    value: Adam
